### ISSUE TITLE
[Clicking Upload Profile Image w/o an Image Needs Error Handling]

### ISSUE THREAD

**Issue by rvvergara** [efrapp/facebook#7]
Whenever I try to click "Upload profile image" (and likewise "Upload Wallpaper Image") without actually selecting any image results in the ff:

![image](https://user-images.githubusercontent.com/6015315/60061058-0cc06e80-9726-11e9-97d5-bbf42679f473.png)

We need to include error handling in our app for this.

**Comment by userman95** [comment]
ok nice . I also noticed that . This will be 5 minute task by tomorrow :)

**Comment by rvvergara** [comment]
Great! This is already resolved! :)
